### ISSUE TITLE
All blocked sites and settings got removed and reset?

### ISSUE THREAD

**Issue by lyuboy** [proginosko/LeechBlockNG#75] opened 2018-08-27 09:35 UTC
For some reason, all of blocked websites that I had setup are now gone.
Does anyone know if there is an auto backup file somewhere (on Windows) to restore the previous settings?

**Comment by proginosko** [comment] 2018-08-27 16:05
This is a known issue (#63) and unfortunately I haven't got to the bottom of it yet. It seems that some users have lost their settings after Firefox crashes or doesn't close properly. It may also happen rarely when the extension is updated to a new version.

If you have an automatic backup service (e.g. Carbonite) you may be able to recover your settings. LB doesn't make its own backup I'm afraid. In future, I recommend making a backup of your settings using the "Export Options to File" feature (Options > General).

**Comment by tngreene** [comment] 2018-09-17 13:33
I have a theory about this issue: It seems to happen after the browser updates (but I'm using Waterfox, so, maybe it is different)

**Comment by lyuboy** [comment] 2018-09-17 20:20
Thank you guys for the reply, I suspect also that it might betwee happen when the browser (in my case Mozilla) updates. I have now exported a backup file, if it happens again.

**Comment by nocibambi** [comment] 2018-11-19 20:57
Just happened to me today (again). I am on Ubuntu 18.04, Firefox 63.0 (64-bit). Will try the backup.

**Comment by lyuboy** [comment] 2018-11-19 21:17
Yes, I would definitely recommend a backup, even though it hasn't happened to me again since the last time I wrote, and I have had firefox update multiple times, but if it happens it's good to be safe and save some time :)

**Comment by proginosko** [comment] 2018-11-19 23:49
Have you tried using sync storage instead as a workaround? Options > General > Miscellaneous

**Comment by nocibambi** [comment] 2018-11-20 08:47
> Have you tried using sync storage instead as a workaround? Options > General > Miscellaneous

I just noticed this option yesterday. How does it work? I do not find documentation about it.

**Comment by proginosko** [comment] 2018-11-21 18:16
Firefox uses two types of storage for extensions: [local](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local) (usually the default) and [sync](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync). When sync storage is used in conjunction with Firefox Sync (see Options > Firefox Account > Sync Settings) your extension settings will be synchronized across browsers and devices. However, if you haven't checked Add-ons under Sync Settings, sync storage should function just like local storage.

My point is that I haven't been able to determine what is causing the lost settings for some users, but using sync storage instead of local storage _could_ be a workaround for now. It's worth a try! (But still create a backup of your LeechBlock options just in case.)

**Comment by mnoukhov** [comment] 2018-11-29 02:00
I have this problem with syncing enabled and addons synced, will try with syncing enabled and addon syncing disabled (Firefox 63.0.3, Fedora 29)

Note: I don't seem to have this issue on Android 8.1 with Firefox 63.0.2, perhaps because Firefox on Android doesn't have addon syncing

**Comment by Erudition** [comment] 2018-12-12 16:02
We should probably close/merge this as duplicate of #63 .
And yes, it happens to me too. Just did.
And yes, it's definitely from Firefox not closing in the "proper" way.

**Comment by mnoukhov** [comment] 2018-12-12 16:30
Syncing enabled but addon syncing disabled seems to have fixed this for me. Will update if anything changes

**Comment by proginosko** [comment] 2018-12-14 22:00
Duplicate of #63

**Closed by proginosko** 2018-12-14 22:00 UTC
