### ISSUE TITLE
Firefox 56 becomes very slow after installing the addon

### ISSUE THREAD

**Issue by dbogdanov** [proginosko/LeechBlockNG#7] opened 2017-11-14 12:19 UTC
Firefox 56 becomes very slow after installing LeechBlockNG 0.4 addon on Ubuntu. Disabling the addon fixes the issue. How can I diagnose the issue and report you additional details properly?

**Comment by proginosko** [comment] 2017-11-14 18:33
Thanks for this report. Try opening the Browser Console (Ctrl+Shift+J), clear the log, then see if any JS error messages appear that might be connected to LeechBlock. If an error message appears every second, that could be caused by LB, which processes tabs every second.

Do you have a long list of block sites? That could also be an issue.

**Comment by dbogdanov** [comment] 2017-11-20 17:36
My list of blocked sites is very short, so this is not an issue. 

Here's a screenshot of Browser Console
![errors](https://user-images.githubusercontent.com/409668/33032102-8953c9cc-ce20-11e7-967f-9d79cb75b48d.png)

**Comment by proginosko** [comment] 2017-11-20 23:29
Thanks, that's helpful. I have some theories about what's causing the problem. I suspect the "Could not establish connection" errors are being generated by LB. Could you try clearing the log (trashcan icon) and seeing if that error comes up once every second? (Watch for the red-circled numbers increasing.)

Another question: Are you accessing mozilla.org websites in any of your tabs?

**Comment by dbogdanov** [comment] 2017-11-21 12:49
They should be generated by LB because if I deactivate it no messages are generated anymore. Number of repeats (the number highlighted in red) is increasing being updated every second. New "Error: Could not establish connection" appears every 4-7 seconds.

**Comment by proginosko** [comment] 2017-11-21 17:35
Thanks again. I've located the cause of the issue. It should be fixed in the next release.

**Closed** 2017-11-28 22:55 UTC
