### ISSUE TITLE
Time counted incorrect

### ISSUE THREAD

**Issue by sirati** [proginosko/LeechBlockNG#148] opened 2020-06-02 08:00 UTC
when having the option "Count time spent on these sites only when browser tab is active" off and having multiple tabs open time spend is incorrectly measured. After switching to another tab that falls under the same list suddenly the reminding time goes does by a couple minutes. i could be that time spend is counted twice, however there does not seem to be linear relationship between tabs open and time being counted too much.

the two times i actively tested this while using my phone as a stop watch i got the following results: 40min -> over after 26 minutes
17min -> over after 12 minutes. 

as i organically used the browser during these experiments, i cannot not testify how many tabs i had open at the same time on average

**Comment by proginosko** [comment] 2020-08-11 18:44
This should be fixed in version 1.0.6.1. If you find otherwise, reopen this issue.

**Comment by sirati97** [comment] 2021-02-02 16:30
@proginosko There seems to be a regression. The problem returned

**Comment by proginosko** [comment] 2021-02-03 02:22
Is this different from #150?

**Comment by sirati97** [comment] 2021-02-03 09:54
yes this is different #150 seems to be fixed as far as i can tell

**Comment by proginosko** [comment] 2021-02-07 21:54
I haven't been able to reproduce this issue. Which OS are you using and which version of FF?

Please provide a series of steps I can use to reproduce the issue (block set settings, tabs to open, etc.).

**Comment by sirati97** [comment] 2021-02-08 20:47
I am using it on Win10/ Firefox 85.0.1 (64-bit)

My current setup is allowing myself to Twitter for 5 minutes every 3 hours. I want to avoid circumventing the timelimit by not having the browser window focussed while scrolling.

However using "Count time spent on these sites only when browser tab is active" as off results in problems when i open multiple taps open with twitter.

after switching between the tabs the timer suddenly jumps to a much lower remaining time. it seems as if each tab on their own counts the time, so having 2 tabs effectively counts the time at 2x speed, 3 tabs 3x speed etc, but it only gets updated upon switching between tabs or closing a tab resulting in switching to another tab from the same blockset.

Steps to reproduce:
-make blockset including website A
- set "Count time spent on these sites only when browser tab is active" to off 
- open two tabs with website A
- wait 10 seconds
- close one tab, so that the other tab on website A opens
- time will be counted down by 20 seconds.

i can make a video demonstrating the issue if needed

**Comment by proginosko** [comment] 2021-02-09 02:15
Thanks for the follow-up. Unfortunately, I haven't been able to reproduce the issue. I created a block set for Twitter allowing 10 minutes every hour, and I unchecked "Count time spent on these sites only when browser tab is active". I opened multiple tabs with Twitter, but when I switch between them, or close one of the tabs, the time is still updated consistently (no jumps).

A video showing the issue would certainly be helpful, if you don't mind taking the trouble.

By the way, the General option "Treat browser windows as always focused" may offer a better solution to your original problem (scrolling while browser window isn't focused).

**Closed** 2021-07-04 20:06 UTC
