### ISSUE TITLE
show matching condition

### ISSUE THREAD

**Issue by ke352802081770314** [proginosko/LeechBlockNG#205] opened 2021-04-09 10:10 UTC
I noticed that recently the option "Show matched keyword on blocking page" was added.
However, I did not see any additional information on the blocking page. I tried to re-generate the blocking page by switching to delay page and back (in cae my setting was using an older template or a parameter to the URL had to be included), no difference. 
Then it occurred to me that by "keyword" you might mean specifically the ~ style of fulltext matching, and I was blocking by domain wildcard. Still I think also in that case it would be helpful to identify the blocking condition, especially if there was an unexpected match due to a too general wildcard term.
So, I am submitting this as a suggestion.
Many thanks for creating and maintaining Leechblock!

**Comment by proginosko** [comment] 2021-06-02 00:42
Yes, that option refers only to cases where the user is blocking by keywords.

I wonder what further information you would need to see for the blocking condition, since the blocking page shows both the URL of the page blocked and also the block set.

**Comment by gary02** [comment] 2021-09-02 10:09
I use `**keyword` instead of `~keyword`,  as I want to wildcard the query string .  But the option "Show matched keyword on blocking page"  seem not work in the case of `**keyword`.

**Comment by gary02** [comment] 2021-09-02 10:29
I use `**keyword` to match urls. Sometime the matched url is too long and it take time to figure out which `**keyword` (I have 30+ such rules) is working.

**Comment by proginosko** [comment] 2021-09-02 20:40
So what would you want to see on the blocking page in that case?

**Comment by gary02** [comment] 2021-09-03 07:49
Blocking pages showing the working rule would be helpful. 
For example, It's `**news` blocking the `https://www.google.com/search?q=news` page，so  the resulting blocking page can display that the `**news` is the cause. 
Thank you for your time！

**Comment by proginosko** [comment] 2021-09-05 19:39
Okay, thanks. The problem is that all the 'rules' are bundled into one regular expression, against which the URL is tested, and it's not straightforward to work backwards and extract the particular 'rule' that caught the URL. The alternative would be to test the URL against each rule separately, but that would really slow things down for users with a long list of sites.

**Comment by gary02** [comment] 2021-09-07 03:57
> The problem is that all the 'rules' are bundled into one regular expression, against which the URL is tested.

Ok, I get it . Thank you for your explanation:D

**Comment by proginosko** [comment] 2021-09-07 17:42
I'm going to close this issue for now, but I will add this to the "wish list" for future reference.

**Closed by proginosko** 2021-09-07 17:42 UTC
