### ISSUE TITLE
Unable to Use Blocked Sites in Private Tabs 

### ISSUE THREAD

**Issue by RithvikIruganti** [proginosko/LeechBlockNG#445] opened 2024-05-18 14:41 UTC
When I choose only non-private tabs option for block . I cant use those sites in private tabs. This is in Firefox browser. Can you help me fix this issue. I cant just disable access to private tabs because i have another block which is for private tabs

**Comment by proginosko** [comment] 2024-05-18 18:20
Please export your options to a text file (Options > General > Export Options) and email it to me at leechblockng@proginosko.com so I can take a closer look.

**Comment by proginosko** [comment] 2024-05-22 13:41
Thanks for sending your options. I think this is due to a bug that has been fixed in version 1.6.4.1 (currently under review for addons.mozilla.org). I recommend waiting until that version is published, then update your version and see if the problem is resolved.

**Closed** 2024-05-22 16:51 UTC
