### ISSUE TITLE
Extension disappears from android extension store after update because the new version isn't compatible

### ISSUE THREAD

**Issue by TheHypeTrain** [proginosko/LeechBlockNG#337] opened 2023-12-05 05:06 UTC
The latest version of Leechblock NG is not (yet) compatible with android, and after I accidentally deleted it it doesn't show up under "Find more add-ons". https://addons.mozilla.org/en-US/android/addon/leechblock-ng/ still exists, but the "Add to firefox" button is greyed out. When I go to https://addons.mozilla.org/en-US/android/addon/leechblock-ng/versions/ https://addons.mozilla.org/en-US/android/addon/leechblock-ng/versions/ it shows old versions and lets me download them, but there is no way to add it to Firefox for Android.

**Comment by proginosko** [comment] 2023-12-05 16:00
Some explanation here:

https://www.tapatalk.com/groups/leechblock/leechblock-on-firefox-android-not-closing-tabs-t682.html#p2461

**Comment by PureRumble** [comment] 2023-12-07 04:29
Developer has disabled Leechblock NG for Firefox Android, but you can still install it.

1. On Firefox Android, go to this link: [Firefox Desktop's extension page for Leechblock NG](https://addons.mozilla.org/en-US/firefox/addon/leechblock-ng/) (do *NOT* go to Firefox Android's extension page by mistake, follow the link instead)
2. When on the page, go to Firefox Android's main menu (icon with three dots next to the address bar) >> enable option "Desktop site" (by tapping it)
3. Now, on the page, tap the link "Add to Firefox"

**Comment by GBHU753** [comment] 2023-12-07 06:01
@PureRumble Thanks, good work around solution for now :) .

**Comment by TheHypeTrain** [comment] 2023-12-09 08:49
Do you think someone could turn a previous version into a fork, and put it onto addons.mozilla.org? I know the developer said that Mozilla wants everything to be Manifest v3, would they reject the fork? 
P.S. thanks for the workaround

**Comment by PureRumble** [comment] 2023-12-09 15:57
> Do you think someone could turn a previous version into a fork, and put it onto addons.mozilla.org? I know the developer said that Mozilla wants everything to be Manifest v3, would they reject the fork? P.S. thanks for the workaround

I humbly propose that we wait instead. The problem is caused by a bug in Firefox for Android, not in the extension itself. The dev is currently in touch with the Firefox team to resolve this problem. He said so eight days ago (https://www.tapatalk.com/groups/leechblock/viewtopic.php?p=2476#p2476).

So how about we wait first for a while and see what happens? 🙂

**Comment by proginosko** [comment] 2023-12-09 17:30
I've uploaded a new version (1.6.1) to AMO and marked it compatible with Firefox for Android. The problems with Manifest V3 will remain until Mozilla fix them, but at least it will be available to install.

**Comment by PureRumble** [comment] 2023-12-10 01:08
Perhaps you should mark this Issue as being resolved/close? And write a note in the extensions description (for Firefox Android) that explains what known unresolved bugs there are and how they work (if you have time)?

**Comment by proginosko** [comment] 2023-12-11 16:09
I don't think there is a separate description for the Android version. The same page (and description) on AMO is used for all versions. I'll close this issue once I've confirmed that the extension is available again for Android.

**Comment by proginosko** [comment] 2023-12-12 16:28
The extension (v1.6.1) is available again for Android on AMO, although the issue with the timer not appearing on a website (until you open one of the extension pages) is not yet resolved.

**Closed by proginosko** 2023-12-12 16:28 UTC
