### ISSUE TITLE
Countdown doesn't work when delaying a page

### ISSUE THREAD

**Issue by marek95** [proginosko/LeechBlockNG#61] opened 2018-04-02 13:27 UTC
when using both a delay and showing a countdown on a page, the counter only shows the time left on first load of the page, does not count down.

**Comment by proginosko** [comment] 2018-04-02 13:49
That's working as intended. The countdown shows you the amount of time left until the pages will start to be delayed.

**Comment by marek95** [comment] 2018-04-02 15:46
I mean that the time isn't moving, it shows the time left when i first load the page, and it stays like that... it isn't decreasing every second ... that's the case for me if I use a few seconds delay before loading the page. in case I don't use delay, its counting down like it should 

to achieve this I have the website in 2 block sets. one is just for that 5 second delay all day, and second _block set_ is set to allow only 10 minutes daily.

**Comment by proginosko** [comment] 2018-04-02 23:52
If you have the same site in two block sets, where the blocking conditions overlap, that could be the issue. Please export your settings to a text file and email them to me (leechblockng@proginosko.com). If you don't want to share all your settings, just create a minimal case and send that.

**Comment by marek95** [comment] 2018-04-07 12:07
sent

**Comment by proginosko** [comment] 2018-04-18 23:49
Sorry for the delay in replying. I see what's happening here. Technically, because of your second block set ("always block with delaying page") LB thinks that the time left for the page is always zero. (If a site appears in multiple block sets, LB calculates the time left for each block set and then displays the _lowest_ of those values, which in your case is always zero.) This isn't so much a bug as it is a usage limitation. 😃 

I can't think of a good workaround at this time. I will make a note and see if I can make LB 'smarter' in future.

**Comment by mattiasJohnson** [comment] 2020-07-03 11:06
I'll bump this issue to provide some more information and also check if a part of it is solvable.

Semi-workaround from the forum (still doesn't show countdown and you have to change pages to apply blocking of site where time has run out):

> In principle, the way to do this would be to put the time limit in the first block set (no time periods, time limit specified, default blocking page) and the delay in the second block set (all-day time period, no time limit, delaying page). However, due to a known issue, this does not work exactly as expected. The delaying will work, but the timer will not be seen to go down. Even so, the amount of time spent on the pages is still being tracked. So if you exceeded your time limit, then went to some other website, and then back to the time-limited website, you should see it completely blocked.
([tapatalk.com](https://www.tapatalk.com/groups/leechblock/viewtopic.php?p=935#p935))

If this is a usage limitation with the countdown, would it at least be possible to make it so that you don't have to switch tabs for the blocking (after time has run out) to apply? I'm playing a browser game so I'm never switching tabs

**Comment by proginosko** [comment] 2020-07-05 21:12
> If this is a usage limitation with the countdown, would it at least be possible to make it so that you don't have to switch tabs for the blocking (after time has run out) to apply? I'm playing a browser game so I'm never switching tabs

Do you have the option "Immediately block pages" selected for the first block set?

**Comment by proginosko** [comment] 2020-10-25 18:32
This should be fixed in version 1.0.7.1. Make sure the block-after-time-limit set _precedes_ the always-delay set in the order of sets.

**Closed by proginosko** 2020-10-25 18:32 UTC
