### ISSUE TITLE
Bugged when two delay pages are applied at the same time

### ISSUE THREAD

**Issue by gepz** [proginosko/LeechBlockNG#282] opened 2022-12-05 21:51 UTC
The countdown just keeps alternating between different delay pages and never ends.

**Comment by proginosko** [comment] 2022-12-05 23:22
What do you think should be the expected behavior in that case?

**Comment by gepz** [comment] 2022-12-06 00:01
I think the same delay page should not be shown again before the user get into the web page they want to see.

Might also be a good idea to fuse multiple delay pages into one and make them countdown at the same time.

**Comment by proginosko** [comment] 2022-12-06 02:10
I would have thought the expected behavior would be that only the first delay (in the order of block sets) takes effect.

**Comment by gepz** [comment] 2022-12-06 02:48
Well, different delays might have different countdown time and different options.
Counting down together would have the effect as only applying the first one when all of them are identical.

**Comment by proginosko** [comment] 2023-02-05 20:26
Duplicate of #173.

**Closed by proginosko** 2023-02-05 20:26 UTC
